results_dir: /results

dataset:
  train_data: /data/results/images
  val_data: /data/results/images
  num_classes: 1
  batch_size: 4
  workers: 8
  category: "pallet"
  num_symmetry: 1
  max_objs: 10

train:
  num_gpus: 1
  validation_interval: 20
  checkpoint_interval: ${train.validation_interval}
  num_epochs: 40
  clip_grad_val: 100.0
  seed: 317
  pretrained_model_path: /results/pretrained_models/centerpose_vtrainable_fan_small/centerpose_trainable_FAN_small.pth
  precision: "fp32"

  optim:
    lr: 6e-05
    lr_steps: [90, 120]

model:
  down_ratio: 4
  use_pretrained: False
  backbone:
    model_type: fan_small
    pretrained_backbone_path: /results/pretrained_models/centerpose_vtrainable_fan_small/centerpose_trainable_FAN_small.pth
